url: "https://budgetyourbudget.com"   # your domain
baseurl: ""                           # empty for root

#page title
page_title: Budget Your Budget # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 6472663180 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: https://play.google.com/store/apps/details?id=com.evelez.byb # Enter Google Play Store URL.
presskit_download_link:# Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: A friendly daily budgeting app that helps you track spending, plan monthly expenses, and stay on top of your goals. Add income, set limits, create custom categories, and see how much you have left—all in a fun, simple, and motivating experience.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Eduardo Velez
your_link: https://www.linkedin.com/in/eduardo-velez-bb108976/
your_city: Puerto Rico
email_address: bybsupport@budgetyourbudget.com
linkedin_username:
linkedin_company:
facebook_username:
instagram_username: edvelezpr
twitter_username:
github_username: edupr90
youtube_username:
mastodon_link:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Daily Budget Tracking
    description: Easily track your daily spending and stay within your set limits for each category.
    fontawesome_icon_name: calendar-day

  - title: Monthly Planning
    description: Plan your monthly budget with recurring and custom categories, and adjust it anytime.
    fontawesome_icon_name: calendar-alt

  - title: Add Income Easily
    description: Add your income after taxes and immediately start planning your spending.
    fontawesome_icon_name: wallet

  - title: Custom Categories
    description: Create custom categories with your own name, emoji, and color.
    fontawesome_icon_name: tags

  - title: One-Tap Transactions
    description: Add your expenses in seconds with simple inputs, auto date selection, and validation.
    fontawesome_icon_name: plus-circle

  - title: Real-Time Budget Left
    description: See how much income is left to budget at a glance after every change.
    fontawesome_icon_name: eye

  - title: Recurring Categories
    description: Set up recurring categories once and have them automatically apply every month.
    fontawesome_icon_name: sync-alt

  - title: Recurring Expenses
    description: Track subscriptions and bills with recurring expenses that repeat each month.
    fontawesome_icon_name: redo-alt

  - title: Reports & Insights
    description: View simple reports to see where your money goes and how your budget is doing.
    fontawesome_icon_name: chart-pie

  - title: Motivation Boosters
    description: Get daily financial affirmation quotes to keep you inspired and mindful.
    fontawesome_icon_name: heart

  - title: Dark Mode Ready
    description: Enjoy a clean, easy-on-the-eyes interface with full dark mode support.
    fontawesome_icon_name: moon

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headercolor2.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.3

device_color: blue # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  #- CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
