import LegalLayout from '../components/LegalLayout';

/*
 * ============================================================
 *  PRIVACY POLICY  —  budgetyourbudget.com/privacypolicy
 *
 *  REWRITTEN 2026-09-22. The previous version stated that all
 *  data stays on the device and is never sent to a server. That
 *  stopped being true when accounts, cloud sync, the Shared
 *  Budget and the AI features shipped. Every data flow below was
 *  verified against the shipping app's source before it was
 *  written down. Do not edit this file from a design document —
 *  check the code.
 * ============================================================
 */

const SUPPORT = 'bybsupport@budgetyourbudget.com';

function Mail() {
  return <a href={`mailto:${SUPPORT}`}>{SUPPORT}</a>;
}

function Ext({ href, children }) {
  return (
    <a href={href} target="_blank" rel="noopener noreferrer">
      {children}
    </a>
  );
}

/* ── ENGLISH ──────────────────────────────────────────────── */

const EN = (
  <>
    <h1>Privacy Policy — <em>Budget Your Budget</em></h1>

    <div className="not-prose my-8 rounded-2xl border border-brand-200 dark:border-brand-800/60 bg-brand-50 dark:bg-brand-950/30 p-5 sm:p-6">
      <p className="text-sm font-bold text-brand-900 dark:text-brand-200 uppercase tracking-wide mb-3">
        The short version
      </p>
      <ul className="text-sm text-brand-900/90 dark:text-brand-100/90 leading-relaxed space-y-2 list-disc pl-5">
        <li>
          <strong>You can use Budget Your Budget without an account.</strong> If you never sign in,
          your budget data stays on your device and we never receive it.
        </li>
        <li>
          <strong>If you sign in, things change.</strong> Signing in creates an account with us and
          uploads your name and profile photo. Cloud sync, which needs a BYB+ subscription or a
          shared budget, then copies your budget data to our servers.
        </li>
        <li>
          <strong>A Shared Budget shows your finances to another person</strong> — including expense
          notes, receipt photos and your income. That is what the feature is for.
        </li>
        <li>
          <strong>Receipt scanning and AI Advice send data to Google</strong> to be processed,
          including the receipt photograph itself.
        </li>
        <li>
          <strong>We never see your bank logins.</strong> The App does not connect to any bank, and
          we never ask for banking credentials or card numbers.
        </li>
        <li>
          <strong>We do not sell your data</strong>, and we do not show you ads.
        </li>
      </ul>
      <p className="text-xs text-brand-900/70 dark:text-brand-200/70 mt-4">
        This summary is here to help you. It is not a substitute for the full policy below.
      </p>
    </div>

    <h2>1. Who we are</h2>
    <p>
      Budget Your Budget (&ldquo;<strong>the App</strong>&rdquo;) is operated by{' '}
      <strong>Eduardo Velez</strong>, an independent software developer based in the Commonwealth of
      Puerto Rico, United States (&ldquo;<strong>we</strong>&rdquo;, &ldquo;<strong>us</strong>&rdquo;).
      We are the controller of the personal data described in this policy. You can reach us at{' '}
      <Mail />.
    </p>
    <p>
      This policy explains what the App collects, when, where it goes, and what you can do about it.
      It applies to the mobile app and to budgetyourbudget.com. Your use of the App is also governed
      by our <a href="/terms">Terms of Use</a>.
    </p>

    <h2>2. The App is local-first, but not local-only</h2>
    <p>
      The App stores your budget in a database on your own device, and it works fully offline. What
      determines whether any of it reaches us is <strong>whether you sign in</strong>:
    </p>
    <ul>
      <li>
        <strong>Never signed in.</strong> Your income, categories, expenses, notes, receipt photos
        and debts stay on your device. We have no copy and no way to reach them. If you delete the
        App or reset your device, that data is gone and we cannot restore it.
      </li>
      <li>
        <strong>Signed in.</strong> An account is created for you with Google or Apple, and your
        display name and profile photo are uploaded so that a shared budget can show who is who.{' '}
        <strong>This happens whether or not you subscribe.</strong>
      </li>
      <li>
        <strong>Signed in, with cloud sync active.</strong> Cloud sync runs when you are signed in{' '}
        <em>and</em> you either have a BYB+ subscription or have joined someone&apos;s shared budget.
        Your budget data is then copied to our cloud and kept in step across your devices. There is
        no separate on/off switch: those two conditions are the switch.
      </li>
    </ul>
    <p>
      Signing in is optional and skippable, and you can keep using the App without ever doing it.
    </p>

    <h2>3. What we collect</h2>

    <h3>3.1 Information you enter</h3>
    <p>
      The App holds the budget information you type in: your income amounts, category names and
      planned amounts, expenses (name or merchant, amount, date, category), free-text notes on
      expenses, receipt photographs you attach, debts and debt payments, and your app settings. This
      lives on your device. It is uploaded to our cloud only when cloud sync is active, as described
      in Section 2.
    </p>

    <h3>3.2 Account information</h3>
    <p>When you sign in with Google or Apple, we receive and store:</p>
    <ul>
      <li>a <strong>user ID</strong> assigned by Firebase Authentication;</li>
      <li>your <strong>display name</strong> and <strong>profile photo</strong> (from your provider,
        or one you choose in the App).</li>
    </ul>
    <p>
      <strong>We do not store your email address.</strong> It is read from your sign-in session only
      to display it to you on screen, and it is never written to our database or shared with anyone.
      If you use Apple&apos;s Hide My Email, we never see your real address at all.
    </p>
    <p>
      Your user ID is also written onto the expenses and income entries you create, so that a shared
      budget can show who entered what.
    </p>

    <h3>3.3 What cloud sync stores</h3>
    <p>When cloud sync is active, the following are copied to our cloud database:</p>
    <ul>
      <li>
        <strong>Expenses</strong> — name or merchant, amount, date, category, colour, recurring flag,{' '}
        <strong>your free-text notes</strong>, a reference to any receipt photo, and who created it;
      </li>
      <li>
        <strong>Income</strong> — amount, amount remaining, month, and whose income it is;
      </li>
      <li>
        <strong>Categories and plans</strong> — planned and remaining amounts, month, colour, emoji,
        and how a category is split between members;
      </li>
      <li>
        <strong>Recurring templates</strong> and <strong>custom categories</strong>;
      </li>
      <li>
        <strong>Debts, debt payments and payoff plans</strong> — name, type, balance, interest rate,
        due date, minimum and target payments, and payment history;
      </li>
      <li>
        <strong>App settings</strong> — language, currency, theme, colour palette, and the flags that
        remember which screens and tips you have already seen;
      </li>
      <li>
        <strong>Saved AI Advice</strong> — the text of AI coaching responses you have generated,
        which restate your own financial figures;
      </li>
      <li>
        <strong>Receipt photographs</strong> and your <strong>profile picture</strong>, stored as
        image files in our cloud storage.
      </li>
    </ul>
    <p>
      <strong>Never uploaded, under any circumstances:</strong> your app PIN, your recovery PIN, your
      biometric-lock setting, and your onboarding survey answers. These stay on your device.
    </p>

    <h3>3.4 Shared Budget</h3>
    <p>
      If you create or join a shared budget, <strong>one other person gains access to that
      budget</strong>. The budget is stored under the owner&apos;s account, and both people can read
      and write it. Specifically, the other person can see and change:
    </p>
    <ul>
      <li>every expense in the budget, including its <strong>free-text notes</strong>;</li>
      <li><strong>receipt photographs</strong> attached to those expenses;</li>
      <li>categories, planned amounts, the split between you, and recurring templates;</li>
      <li>
        <strong>both people&apos;s income amounts and the household total</strong> (each person can only
        edit their own income);
      </li>
      <li>your <strong>display name and profile photo</strong>, next to each expense you logged.</li>
    </ul>
    <p>
      <strong>Your email address is never shared with the other member.</strong>
    </p>
    <p>
      <strong>Not shared, ever:</strong> your debts, debt payments and payoff plans; your app PIN and
      biometric lock; your settings, theme and language; your reports; and your AI Advice history.
    </p>
    <p>
      To set up a share, the owner creates an invite code. We store a record of that invite — the
      owner&apos;s user ID, its status and timestamps, and, once used, the user ID of the person who
      redeemed it — and a membership record linking the two accounts.{' '}
      <strong>
        Anyone who has a valid code and signs in can redeem it; we do not verify who they are.
      </strong>{' '}
      Treat an invite code like a password.
    </p>
    <p>
      When a member leaves or is removed, the expenses and income they contributed are withdrawn from
      the budget. See Section 7 for how long deleted records persist.
    </p>

    <h3>3.5 AI features</h3>
    <p>
      Two features send data to <strong>Google&apos;s Gemini models</strong> through Firebase AI Logic
      for processing. Both require a BYB+ subscription.
    </p>
    <ul>
      <li>
        <strong>Receipt scanning.</strong> The <strong>photograph of your receipt</strong> is
        transmitted to Google, along with your list of category names, so the total, merchant, date,
        line items and the last four digits of the card shown on the receipt can be read back. The
        image is resized before sending, but{' '}
        <strong>it is the whole photograph, and we do not strip its metadata</strong> — if your photo
        carries location data from your camera, that can travel with it. If you photograph something
        that is not a receipt, that image is still transmitted before it is rejected.
      </li>
      <li>
        <strong>AI Advice and Insights.</strong> A summary of your real finances is transmitted as
        text: spending totals and averages, your largest expense, your top expense names with
        amounts, income figures, budgeted versus spent per category, and your debts with balances,
        interest rates, minimum payments and payment history.
      </li>
    </ul>
    <p>
      When you are signed in, these requests are associated with your account. Google processes this
      data as our service provider under the{' '}
      <Ext href="https://firebase.google.com/terms/data-processing-terms">
        Firebase Data Processing Terms
      </Ext>
      . Please do not photograph documents, or write notes, containing information you do not want
      transmitted for processing.
    </p>

    <h3>3.6 Analytics</h3>
    <p>
      The App uses <strong>Google Firebase Analytics</strong> to understand how features are used so
      we can improve them. We log events such as app opens, onboarding steps completed or skipped,
      screens viewed, paywall views and purchase outcomes, and which feature a person used.
    </p>
    <p>Two things here deserve to be called out plainly:</p>
    <ul>
      <li>
        <strong>Category names can be included.</strong> A few events carry the identifier of the
        category involved, and for a category you created yourself that identifier is{' '}
        <strong>the name you typed</strong>. If you name a category something sensitive, that text can
        reach Google Analytics. If that matters to you, choose neutral category names.
      </li>
      <li>
        <strong>Your onboarding answers become analytics properties.</strong> The main money challenge
        you selected, whether your income is steady or varies, and the goal you chose are recorded as
        properties on your analytics profile.
      </li>
    </ul>
    <p>
      Analytics events are tied to a pseudonymous identifier generated by Google for your app
      installation. <strong>We do not send your user ID, name or email to Analytics.</strong> We do
      not use analytics for advertising, and the App shows no ads.
    </p>
    <p>
      <strong>Analytics is currently enabled by default and the App does not yet offer an in-app
      opt-out.</strong> If you want us to stop processing your analytics data, email us at <Mail />{' '}
      and we will action your request.
    </p>

    <h3>3.7 Subscriptions</h3>
    <p>
      Purchases are processed by <strong>Apple</strong> or <strong>Google Play</strong> — we never see
      your card or payment details. We use <strong>RevenueCat</strong> to check whether your
      subscription is active. Before you sign in, RevenueCat identifies you by an anonymous ID it
      generates; once you sign in, we give RevenueCat your user ID so purchases follow your account.
      We do not send RevenueCat your name or email.
    </p>
    <p>
      When a purchase completes, the product, price and currency are recorded as an analytics event.
      That is the price of the subscription, not any figure about your own money.
    </p>

    <h3>3.8 Notifications, security checks, and fonts</h3>
    <ul>
      <li>
        <strong>Notifications are local.</strong> Reminders and daily summaries are scheduled and
        composed entirely on your device. There is no push service, and their contents — including
        amounts and a partner&apos;s name — never leave your phone.
      </li>
      <li>
        <strong>App integrity.</strong> We use Firebase App Check (Apple App Attest, Google Play
        Integrity) to confirm requests come from a genuine, unmodified copy of the App. It checks the
        app, not you, and does not identify you.
      </li>
      <li>
        <strong>Fonts.</strong> The App and this website load the Inter typeface from Google&apos;s font
        service at runtime, which means Google receives the request, including your IP address.
      </li>
      <li>
        <strong>Remote configuration.</strong> The App fetches one setting from Firebase Remote Config
        (which AI model to use). No information about you is sent to retrieve it.
      </li>
    </ul>

    <h3>3.9 Camera, photos, microphone</h3>
    <p>
      The App asks for camera or photo-library access only when you attach a receipt or choose a
      profile picture, and it accesses only the images you pick. A microphone permission is declared
      for a voice-entry feature that is <strong>currently disabled and unreachable</strong> in the
      App; no audio is recorded or transmitted.
    </p>

    <h2>4. What we never collect</h2>
    <ul>
      <li>
        <strong>Bank credentials, account numbers, or card numbers.</strong> The App does not connect
        to any financial institution and has no ability to move money.
      </li>
      <li>
        <strong>Your app PIN or recovery PIN</strong>, and no biometric data — fingerprints and face
        data are handled entirely by your device&apos;s operating system, which only tells the App
        whether the check passed.
      </li>
      <li>
        <strong>Your precise location.</strong> The App does not request location permission or track
        your location. (See Section 3.5 regarding metadata inside a photo you choose to scan.)
      </li>
      <li>
        <strong>Advertising identifiers.</strong> We serve no ads, run no advertising SDK, and do not
        track you across other apps or websites.
      </li>
      <li>
        <strong>Your contacts, messages, calendar or files.</strong>
      </li>
    </ul>

    <h2>5. How we use information</h2>
    <p>We use the information described above only to:</p>
    <ul>
      <li>provide the App and keep your data in step across your devices;</li>
      <li>operate the Shared Budget feature between you and the person you chose;</li>
      <li>produce the results you asked for from the AI features;</li>
      <li>check whether your subscription is active;</li>
      <li>understand which features are used, so we can improve them and fix problems;</li>
      <li>respond to your support requests;</li>
      <li>protect the App against abuse, fraud and tampering;</li>
      <li>comply with legal obligations.</li>
    </ul>
    <p>
      <strong>We do not sell your personal information</strong>, we do not share it for cross-context
      behavioural advertising, and we do not use your budget data to train AI models of our own.
    </p>
    <p>
      Where the GDPR applies, our legal bases are: <strong>performance of a contract</strong> (running
      the App and the features you turn on), <strong>legitimate interests</strong> (keeping the App
      secure, understanding feature usage), <strong>consent</strong> where we ask for it (device
      permissions such as camera and notifications), and <strong>legal obligation</strong> where
      applicable.
    </p>

    <h2>6. Who we share information with</h2>
    <p>
      We share information only with the following service providers, who process it on our behalf,
      and with the person you choose to share a budget with.
    </p>
    <div className="overflow-x-auto">
      <table>
        <thead>
          <tr>
            <th>Who</th>
            <th>What for</th>
            <th>Their policy</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><strong>Google (Firebase)</strong></td>
            <td>Sign-in, cloud database, file storage, analytics, app integrity, remote config</td>
            <td><Ext href="https://policies.google.com/privacy">Google Privacy Policy</Ext></td>
          </tr>
          <tr>
            <td><strong>Google (Gemini AI)</strong></td>
            <td>Receipt scanning and AI Advice</td>
            <td>
              <Ext href="https://firebase.google.com/terms/data-processing-terms">
                Firebase Data Processing Terms
              </Ext>
            </td>
          </tr>
          <tr>
            <td><strong>Apple</strong></td>
            <td>Sign in with Apple, App Store purchases</td>
            <td><Ext href="https://www.apple.com/legal/privacy/">Apple Privacy Policy</Ext></td>
          </tr>
          <tr>
            <td><strong>RevenueCat</strong></td>
            <td>Subscription status</td>
            <td><Ext href="https://www.revenuecat.com/privacy">RevenueCat Privacy Policy</Ext></td>
          </tr>
        </tbody>
      </table>
    </div>
    <p>
      We may also disclose information if required by law, to respond to valid legal process, or to
      protect the rights, safety or property of our users, the public, or us. If the App is ever
      transferred to another owner, information may transfer with it, and we will say so here first.
    </p>

    <h2>7. Where data is stored, and for how long</h2>
    <ul>
      <li>
        <strong>Location.</strong> Cloud data is stored on Google Cloud infrastructure in the{' '}
        <strong>United States</strong> (region us-east1). If you use the App from outside the United
        States, your information is transferred there. Where required, these transfers rely on the
        European Commission&apos;s Standard Contractual Clauses, which Google&apos;s data processing terms
        incorporate.
      </li>
      <li>
        <strong>While you use the App.</strong> We keep your data for as long as your account exists
        and sync is active.
      </li>
      <li>
        <strong>Deleted entries are not erased instantly.</strong> So that a deletion on one device
        reaches your other device, a deleted record travels as a marker and the underlying record is
        removed from our cloud database <strong>up to 90 days later</strong>. This also applies to the
        entries of a member who leaves a shared budget.
      </li>
      <li>
        <strong>Records that outlive an account.</strong> Invite records and shared-budget membership
        records are kept after an account is deleted. They contain user IDs, timestamps and the
        invite code — no name, email or financial figure. Contact us if you want these removed.
      </li>
      <li>
        <strong>Local data.</strong> Data on your device stays there until you delete it, delete your
        account, or uninstall the App. Signing out does not delete anything.
      </li>
      <li>
        <strong>Our providers.</strong> Google and our other providers may retain data in backups and
        logs under their own schedules, which we do not control.
      </li>
    </ul>

    <h2>8. Security</h2>
    <p>
      Data in transit is protected with TLS, and data at rest in our cloud is encrypted by Google
      Cloud. Access to your cloud data is controlled by server-side security rules tied to your
      account, and — for a shared budget — to the membership you created. Requests to our AI features
      must pass a device-integrity check. Your app PIN, recovery PIN and biometric settings never
      leave your device.
    </p>
    <p>
      <strong>
        We should be straightforward with you about two limits. First, your budget data is not
        end-to-end encrypted:
      </strong>{' '}
      it is stored in a form that we, as the operator of the service, could technically access. We
      access it only when necessary to operate the service, investigate a problem you report, or
      comply with the law. <strong>Second, no method of transmission or storage is completely
      secure</strong>, and we cannot guarantee absolute security. A backup file you export from the
      App is <strong>not encrypted</strong>; keep it somewhere you trust.
    </p>
    <p>
      Please protect your side too: use a device passcode, enable the app lock, and treat a
      shared-budget invite code like a password.
    </p>

    <h2>9. Children</h2>
    <p>
      The App is not directed to children under 13, and we do not knowingly collect personal
      information from them. Our <a href="/terms">Terms of Use</a> require account holders to be 18
      or older; a person aged 13 to 17 may use the App only under the supervision of a parent or
      guardian who accepts the Terms on their behalf. If you believe a child under 13 has provided us
      with personal information, contact us at <Mail /> and we will delete it.
    </p>

    <h2>10. Your rights and choices</h2>
    <p>You can act on your data directly in the App:</p>
    <ul>
      <li>
        <strong>See and export it.</strong> Profile → Backup &amp; Import exports your whole dataset
        as a file. Note the export is not encrypted.
      </li>
      <li>
        <strong>Correct it.</strong> Every entry is editable in the App.
      </li>
      <li>
        <strong>Delete your account and your cloud data.</strong> Profile → your account card →
        Delete account. This erases your cloud data, your uploaded receipt images, your account
        itself, and your data on that device. It cannot be undone, and it is refused while another
        member is still in your shared budget — remove them first.
      </li>
      <li>
        <strong>Stop sharing.</strong> Leave or end a shared budget at any time from the Shared Budget
        screen.
      </li>
      <li>
        <strong>Stop syncing.</strong> Sign out, or let a subscription lapse. Signing out leaves your
        cloud copy in place; use Delete account to remove it.
      </li>
      <li>
        <strong>If you never signed in</strong>, there is no cloud copy to delete. Uninstalling the App
        removes your data from the device.
      </li>
      <li>
        <strong>Device permissions</strong> — camera, photos and notifications — can be changed at any
        time in your device settings.
      </li>
    </ul>
    <p>
      Depending on where you live, you may have rights to <strong>access</strong>, <strong>correct</strong>,{' '}
      <strong>delete</strong>, <strong>port</strong>, <strong>restrict</strong> or{' '}
      <strong>object to</strong> our processing of your personal data, to{' '}
      <strong>withdraw consent</strong>, and to be free from discrimination for exercising those
      rights. Residents of the EU, the UK, California and other US states with privacy laws have
      these rights under the GDPR, the UK GDPR, the CCPA/CPRA and comparable laws.
    </p>
    <p>
      To exercise any of them, email <Mail />. We will verify your request using the account it comes
      from and respond within the time the applicable law requires. Using these rights costs nothing,
      and we will not treat you differently for it. EU and UK users also have the right to complain
      to their local data protection authority.
    </p>

    <h2>11. Changes to this policy</h2>
    <p>
      We will update this policy when the App changes. The &ldquo;Last updated&rdquo; date at the top
      shows when. For material changes we will make reasonable efforts to notify you in the App or by
      other means. Please check back from time to time.
    </p>

    <h2>12. Contact</h2>
    <p>Questions, requests, or privacy concerns:</p>
    <p>
      📧 <strong><Mail /></strong>
    </p>
    <p>
      Budget Your Budget — operated by Eduardo Velez, Commonwealth of Puerto Rico, United States.
    </p>
  </>
);

/* ── ESPAÑOL ──────────────────────────────────────────────── */

const ES = (
  <>
    <h1>Política de Privacidad — <em>Budget Your Budget</em></h1>

    <div className="not-prose my-8 rounded-2xl border border-brand-200 dark:border-brand-800/60 bg-brand-50 dark:bg-brand-950/30 p-5 sm:p-6">
      <p className="text-sm font-bold text-brand-900 dark:text-brand-200 uppercase tracking-wide mb-3">
        La versión corta
      </p>
      <ul className="text-sm text-brand-900/90 dark:text-brand-100/90 leading-relaxed space-y-2 list-disc pl-5">
        <li>
          <strong>Puede usar Budget Your Budget sin cuenta.</strong> Si nunca inicia sesión, sus datos
          de presupuesto permanecen en su dispositivo y nosotros nunca los recibimos.
        </li>
        <li>
          <strong>Si inicia sesión, esto cambia.</strong> Iniciar sesión crea una cuenta con nosotros
          y sube su nombre y su foto de perfil. La sincronización en la nube, que requiere una
          suscripción BYB+ o un presupuesto compartido, copia entonces sus datos a nuestros
          servidores.
        </li>
        <li>
          <strong>Un Presupuesto Compartido muestra sus finanzas a otra persona</strong> — incluidas
          las notas de los gastos, las fotos de recibos y su ingreso. Ese es el propósito de la
          función.
        </li>
        <li>
          <strong>El escaneo de recibos y los Consejos con IA envían datos a Google</strong> para su
          procesamiento, incluida la propia fotografía del recibo.
        </li>
        <li>
          <strong>Nunca vemos sus claves bancarias.</strong> La App no se conecta a ningún banco y
          nunca le pedimos credenciales bancarias ni números de tarjeta.
        </li>
        <li>
          <strong>No vendemos sus datos</strong> y no le mostramos anuncios.
        </li>
      </ul>
      <p className="text-xs text-brand-900/70 dark:text-brand-200/70 mt-4">
        Este resumen es una ayuda. No sustituye la política completa que aparece a continuación.
      </p>
    </div>

    <h2>1. Quiénes somos</h2>
    <p>
      Budget Your Budget (&ldquo;<strong>la App</strong>&rdquo;) es operada por{' '}
      <strong>Eduardo Velez</strong>, desarrollador de software independiente radicado en el Estado
      Libre Asociado de Puerto Rico, Estados Unidos (&ldquo;<strong>nosotros</strong>&rdquo;). Somos
      el responsable del tratamiento de los datos personales descritos en esta política. Puede
      contactarnos en <Mail />.
    </p>
    <p>
      Esta política explica qué recopila la App, cuándo, a dónde va y qué puede hacer usted al
      respecto. Aplica a la aplicación móvil y a budgetyourbudget.com. Su uso de la App también se
      rige por nuestros <a href="/terms">Términos de Uso</a>.
    </p>

    <h2>2. La App es local primero, pero no solo local</h2>
    <p>
      La App guarda su presupuesto en una base de datos en su propio dispositivo y funciona
      completamente sin conexión. Lo que determina si algo de eso llega hasta nosotros es{' '}
      <strong>si usted inicia sesión</strong>:
    </p>
    <ul>
      <li>
        <strong>Sin iniciar sesión nunca.</strong> Sus ingresos, categorías, gastos, notas, fotos de
        recibos y deudas permanecen en su dispositivo. No tenemos copia alguna ni forma de acceder a
        ellos. Si elimina la App o restablece su dispositivo, esos datos se pierden y no podemos
        restaurarlos.
      </li>
      <li>
        <strong>Con sesión iniciada.</strong> Se crea una cuenta con Google o Apple y se suben su
        nombre visible y su foto de perfil, para que un presupuesto compartido pueda mostrar quién es
        quién. <strong>Esto ocurre tenga o no una suscripción.</strong>
      </li>
      <li>
        <strong>Con sesión iniciada y sincronización activa.</strong> La sincronización en la nube
        funciona cuando usted ha iniciado sesión <em>y</em> además tiene una suscripción BYB+ o se ha
        unido al presupuesto compartido de alguien. Sus datos de presupuesto se copian entonces a
        nuestra nube y se mantienen sincronizados entre sus dispositivos. No hay un interruptor
        aparte: esas dos condiciones son el interruptor.
      </li>
    </ul>
    <p>
      Iniciar sesión es opcional y se puede omitir; puede seguir usando la App sin hacerlo nunca.
    </p>

    <h2>3. Qué recopilamos</h2>

    <h3>3.1 Información que usted introduce</h3>
    <p>
      La App guarda la información de presupuesto que usted escribe: montos de ingresos, nombres de
      categorías y montos planificados, gastos (nombre o comercio, monto, fecha, categoría), notas de
      texto libre en los gastos, fotografías de recibos que adjunte, deudas y pagos de deudas, y sus
      ajustes. Todo eso reside en su dispositivo. Se sube a nuestra nube únicamente cuando la
      sincronización está activa, según lo descrito en la Sección 2.
    </p>

    <h3>3.2 Información de la cuenta</h3>
    <p>Cuando inicia sesión con Google o Apple, recibimos y almacenamos:</p>
    <ul>
      <li>un <strong>identificador de usuario</strong> asignado por Firebase Authentication;</li>
      <li>
        su <strong>nombre visible</strong> y su <strong>foto de perfil</strong> (de su proveedor, o la
        que elija en la App).
      </li>
    </ul>
    <p>
      <strong>No almacenamos su dirección de correo electrónico.</strong> Se lee de su sesión
      únicamente para mostrársela en pantalla, y nunca se escribe en nuestra base de datos ni se
      comparte con nadie. Si usa la función Ocultar mi correo de Apple, nunca vemos su dirección
      real.
    </p>
    <p>
      Su identificador de usuario también se escribe en los gastos e ingresos que crea, para que un
      presupuesto compartido pueda mostrar quién registró qué.
    </p>

    <h3>3.3 Qué almacena la sincronización en la nube</h3>
    <p>Cuando la sincronización está activa, se copia a nuestra base de datos en la nube:</p>
    <ul>
      <li>
        <strong>Gastos</strong> — nombre o comercio, monto, fecha, categoría, color, marca de
        recurrencia, <strong>sus notas de texto libre</strong>, una referencia a la foto del recibo y
        quién lo creó;
      </li>
      <li><strong>Ingresos</strong> — monto, monto restante, mes y de quién es el ingreso;</li>
      <li>
        <strong>Categorías y planes</strong> — montos planificados y restantes, mes, color, emoji y
        cómo se reparte una categoría entre los miembros;
      </li>
      <li><strong>Plantillas recurrentes</strong> y <strong>categorías personalizadas</strong>;</li>
      <li>
        <strong>Deudas, pagos y planes de pago</strong> — nombre, tipo, saldo, tasa de interés, fecha
        de vencimiento, pagos mínimos y objetivo, e historial de pagos;
      </li>
      <li>
        <strong>Ajustes de la App</strong> — idioma, moneda, tema, paleta de color y las marcas que
        recuerdan qué pantallas y consejos ya ha visto;
      </li>
      <li>
        <strong>Consejos de IA guardados</strong> — el texto de las respuestas de IA que haya
        generado, que reexponen sus propias cifras financieras;
      </li>
      <li>
        <strong>Fotografías de recibos</strong> y su <strong>foto de perfil</strong>, almacenadas como
        archivos de imagen en nuestro almacenamiento en la nube.
      </li>
    </ul>
    <p>
      <strong>Nunca se sube, bajo ninguna circunstancia:</strong> el PIN de la App, el PIN de
      recuperación, su ajuste de bloqueo biométrico y sus respuestas del cuestionario inicial. Todo
      eso permanece en su dispositivo.
    </p>

    <h3>3.4 Presupuesto Compartido</h3>
    <p>
      Si crea o se une a un presupuesto compartido,{' '}
      <strong>otra persona obtiene acceso a ese presupuesto</strong>. El presupuesto se almacena bajo
      la cuenta del propietario y ambas personas pueden leerlo y modificarlo. En concreto, la otra
      persona puede ver y cambiar:
    </p>
    <ul>
      <li>todos los gastos del presupuesto, incluidas sus <strong>notas de texto libre</strong>;</li>
      <li>las <strong>fotografías de recibos</strong> adjuntas a esos gastos;</li>
      <li>las categorías, los montos planificados, el reparto entre ustedes y las plantillas recurrentes;</li>
      <li>
        <strong>los ingresos de ambas personas y el total del hogar</strong> (cada persona solo puede
        editar su propio ingreso);
      </li>
      <li>
        su <strong>nombre visible y su foto de perfil</strong>, junto a cada gasto que usted registre.
      </li>
    </ul>
    <p>
      <strong>Su dirección de correo electrónico nunca se comparte con el otro miembro.</strong>
    </p>
    <p>
      <strong>Nunca se comparte:</strong> sus deudas, pagos y planes de pago; el PIN de la App y el
      bloqueo biométrico; sus ajustes, tema e idioma; sus informes; y su historial de Consejos con
      IA.
    </p>
    <p>
      Para establecer el uso compartido, el propietario crea un código de invitación. Guardamos un
      registro de esa invitación — el identificador del propietario, su estado y fechas y, una vez
      usada, el identificador de quien la canjeó — y un registro de membresía que vincula ambas
      cuentas.{' '}
      <strong>
        Cualquiera que tenga un código válido e inicie sesión puede canjearlo; no verificamos quién
        es.
      </strong>{' '}
      Trate un código de invitación como una contraseña.
    </p>
    <p>
      Cuando un miembro sale o es eliminado, los gastos e ingresos que aportó se retiran del
      presupuesto. Véase la Sección 7 sobre cuánto persisten los registros eliminados.
    </p>

    <h3>3.5 Funciones de inteligencia artificial</h3>
    <p>
      Dos funciones envían datos a los <strong>modelos Gemini de Google</strong> a través de Firebase
      AI Logic para su procesamiento. Ambas requieren una suscripción BYB+.
    </p>
    <ul>
      <li>
        <strong>Escaneo de recibos.</strong> La <strong>fotografía de su recibo</strong> se transmite a
        Google, junto con su lista de nombres de categorías, para poder extraer el total, el comercio,
        la fecha, las líneas de detalle y los últimos cuatro dígitos de la tarjeta que aparece en el
        recibo. La imagen se reduce de tamaño antes de enviarse, pero{' '}
        <strong>es la fotografía completa y no eliminamos sus metadatos</strong> — si su foto lleva
        datos de ubicación de la cámara, estos pueden viajar con ella. Si fotografía algo que no es un
        recibo, esa imagen igualmente se transmite antes de ser rechazada.
      </li>
      <li>
        <strong>Consejos e Insights con IA.</strong> Se transmite como texto un resumen de sus
        finanzas reales: totales y promedios de gasto, su mayor gasto, sus principales nombres de
        gasto con montos, cifras de ingreso, presupuestado frente a gastado por categoría, y sus
        deudas con saldos, tasas de interés, pagos mínimos e historial de pagos.
      </li>
    </ul>
    <p>
      Cuando usted ha iniciado sesión, estas solicitudes quedan asociadas a su cuenta. Google trata
      estos datos como nuestro proveedor de servicios conforme a los{' '}
      <Ext href="https://firebase.google.com/terms/data-processing-terms">
        Términos de Tratamiento de Datos de Firebase
      </Ext>
      . Le rogamos no fotografiar documentos, ni escribir notas, con información que no desee
      transmitir para su procesamiento.
    </p>

    <h3>3.6 Analítica</h3>
    <p>
      La App usa <strong>Google Firebase Analytics</strong> para entender cómo se usan las funciones y
      poder mejorarlas. Registramos eventos como aperturas de la App, pasos completados u omitidos del
      inicio, pantallas vistas, vistas de la pantalla de suscripción y resultados de compra, y qué
      función usó la persona.
    </p>
    <p>Dos cosas merecen decirse con claridad:</p>
    <ul>
      <li>
        <strong>Los nombres de categorías pueden incluirse.</strong> Algunos eventos llevan el
        identificador de la categoría implicada, y para una categoría que usted creó ese identificador
        es <strong>el nombre que usted escribió</strong>. Si nombra una categoría con algo sensible,
        ese texto puede llegar a Google Analytics. Si eso le preocupa, elija nombres neutrales.
      </li>
      <li>
        <strong>Sus respuestas del cuestionario inicial se convierten en propiedades de analítica.</strong>{' '}
        El principal reto financiero que seleccionó, si su ingreso es estable o variable, y la meta que
        eligió se registran como propiedades de su perfil analítico.
      </li>
    </ul>
    <p>
      Los eventos de analítica se asocian a un identificador seudónimo generado por Google para su
      instalación. <strong>No enviamos a Analytics su identificador de usuario, su nombre ni su
      correo.</strong> No usamos la analítica con fines publicitarios y la App no muestra anuncios.
    </p>
    <p>
      <strong>
        La analítica está actualmente activada por defecto y la App todavía no ofrece una opción de
        desactivación dentro de la aplicación.
      </strong>{' '}
      Si desea que dejemos de tratar sus datos analíticos, escríbanos a <Mail /> y atenderemos su
      solicitud.
    </p>

    <h3>3.7 Suscripciones</h3>
    <p>
      Las compras las procesan <strong>Apple</strong> o <strong>Google Play</strong> — nunca vemos su
      tarjeta ni sus datos de pago. Usamos <strong>RevenueCat</strong> para comprobar si su
      suscripción está activa. Antes de que inicie sesión, RevenueCat le identifica con un
      identificador anónimo que genera; una vez inicia sesión, le damos a RevenueCat su identificador
      de usuario para que las compras sigan a su cuenta. No enviamos a RevenueCat su nombre ni su
      correo.
    </p>
    <p>
      Al completarse una compra, se registran el producto, el precio y la moneda como evento de
      analítica. Ese es el precio de la suscripción, no una cifra sobre su propio dinero.
    </p>

    <h3>3.8 Notificaciones, verificaciones de seguridad y tipografías</h3>
    <ul>
      <li>
        <strong>Las notificaciones son locales.</strong> Los recordatorios y resúmenes diarios se
        programan y componen enteramente en su dispositivo. No hay servicio de notificaciones push, y
        su contenido — incluidos montos y el nombre de su pareja — nunca sale de su teléfono.
      </li>
      <li>
        <strong>Integridad de la App.</strong> Usamos Firebase App Check (Apple App Attest, Google Play
        Integrity) para confirmar que las solicitudes provienen de una copia genuina y no modificada
        de la App. Verifica la aplicación, no a usted, y no le identifica.
      </li>
      <li>
        <strong>Tipografías.</strong> La App y este sitio web cargan la tipografía Inter desde el
        servicio de fuentes de Google en tiempo de ejecución, lo que significa que Google recibe la
        solicitud, incluida su dirección IP.
      </li>
      <li>
        <strong>Configuración remota.</strong> La App obtiene un ajuste de Firebase Remote Config (qué
        modelo de IA usar). No se envía información sobre usted para obtenerlo.
      </li>
    </ul>

    <h3>3.9 Cámara, fotos y micrófono</h3>
    <p>
      La App solicita acceso a la cámara o a la fototeca únicamente cuando usted adjunta un recibo o
      elige una foto de perfil, y accede solo a las imágenes que usted selecciona. Existe un permiso de
      micrófono declarado para una función de entrada por voz que está{' '}
      <strong>actualmente desactivada e inaccesible</strong> en la App; no se graba ni transmite audio
      alguno.
    </p>

    <h2>4. Qué nunca recopilamos</h2>
    <ul>
      <li>
        <strong>Credenciales bancarias, números de cuenta o números de tarjeta.</strong> La App no se
        conecta a ninguna institución financiera y no puede mover dinero.
      </li>
      <li>
        <strong>Su PIN de la App ni su PIN de recuperación</strong>, ni datos biométricos — las huellas
        y el reconocimiento facial los gestiona íntegramente el sistema operativo de su dispositivo,
        que solo indica a la App si la verificación fue correcta.
      </li>
      <li>
        <strong>Su ubicación precisa.</strong> La App no solicita permiso de ubicación ni rastrea dónde
        está. (Véase la Sección 3.5 sobre los metadatos dentro de una foto que elija escanear.)
      </li>
      <li>
        <strong>Identificadores publicitarios.</strong> No mostramos anuncios, no usamos ningún SDK
        publicitario y no le rastreamos en otras apps o sitios web.
      </li>
      <li><strong>Sus contactos, mensajes, calendario o archivos.</strong></li>
    </ul>

    <h2>5. Cómo usamos la información</h2>
    <p>Usamos la información descrita únicamente para:</p>
    <ul>
      <li>ofrecer la App y mantener sus datos sincronizados entre sus dispositivos;</li>
      <li>operar la función de Presupuesto Compartido entre usted y la persona que eligió;</li>
      <li>producir los resultados que pidió a las funciones de IA;</li>
      <li>comprobar si su suscripción está activa;</li>
      <li>entender qué funciones se usan, para mejorarlas y corregir problemas;</li>
      <li>responder a sus solicitudes de soporte;</li>
      <li>proteger la App frente a abusos, fraude y manipulación;</li>
      <li>cumplir obligaciones legales.</li>
    </ul>
    <p>
      <strong>No vendemos su información personal</strong>, no la compartimos para publicidad
      conductual entre contextos y no usamos sus datos de presupuesto para entrenar modelos de IA
      propios.
    </p>
    <p>
      Cuando aplica el RGPD, nuestras bases jurídicas son:{' '}
      <strong>la ejecución de un contrato</strong> (hacer funcionar la App y las funciones que usted
      activa), <strong>el interés legítimo</strong> (mantener la App segura, entender el uso de las
      funciones), <strong>el consentimiento</strong> cuando lo solicitamos (permisos del dispositivo
      como cámara y notificaciones) y <strong>la obligación legal</strong> cuando corresponda.
    </p>

    <h2>6. Con quién compartimos información</h2>
    <p>
      Compartimos información únicamente con los siguientes proveedores de servicios, que la tratan
      por cuenta nuestra, y con la persona con quien usted elige compartir un presupuesto.
    </p>
    <div className="overflow-x-auto">
      <table>
        <thead>
          <tr>
            <th>Quién</th>
            <th>Para qué</th>
            <th>Su política</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><strong>Google (Firebase)</strong></td>
            <td>Inicio de sesión, base de datos en la nube, almacenamiento de archivos, analítica, integridad de la app, configuración remota</td>
            <td><Ext href="https://policies.google.com/privacy">Política de Privacidad de Google</Ext></td>
          </tr>
          <tr>
            <td><strong>Google (Gemini IA)</strong></td>
            <td>Escaneo de recibos y Consejos con IA</td>
            <td>
              <Ext href="https://firebase.google.com/terms/data-processing-terms">
                Términos de Tratamiento de Datos de Firebase
              </Ext>
            </td>
          </tr>
          <tr>
            <td><strong>Apple</strong></td>
            <td>Inicio de sesión con Apple, compras en el App Store</td>
            <td><Ext href="https://www.apple.com/legal/privacy/">Política de Privacidad de Apple</Ext></td>
          </tr>
          <tr>
            <td><strong>RevenueCat</strong></td>
            <td>Estado de la suscripción</td>
            <td><Ext href="https://www.revenuecat.com/privacy">Política de Privacidad de RevenueCat</Ext></td>
          </tr>
        </tbody>
      </table>
    </div>
    <p>
      También podemos divulgar información si la ley lo exige, para responder a un proceso legal
      válido, o para proteger los derechos, la seguridad o la propiedad de nuestros usuarios, del
      público o nuestros. Si la App se transfiriera alguna vez a otro propietario, la información
      podría transferirse con ella, y lo indicaríamos aquí previamente.
    </p>

    <h2>7. Dónde se almacenan los datos y por cuánto tiempo</h2>
    <ul>
      <li>
        <strong>Ubicación.</strong> Los datos en la nube se almacenan en infraestructura de Google
        Cloud en los <strong>Estados Unidos</strong> (región us-east1). Si usa la App fuera de los
        Estados Unidos, su información se transfiere allí. Cuando corresponde, estas transferencias se
        amparan en las Cláusulas Contractuales Tipo de la Comisión Europea, que los términos de
        tratamiento de datos de Google incorporan.
      </li>
      <li>
        <strong>Mientras usa la App.</strong> Conservamos sus datos mientras exista su cuenta y la
        sincronización esté activa.
      </li>
      <li>
        <strong>Las entradas eliminadas no se borran al instante.</strong> Para que una eliminación en
        un dispositivo llegue a su otro dispositivo, el registro eliminado viaja como un marcador y el
        registro subyacente se elimina de nuestra base de datos en la nube{' '}
        <strong>hasta 90 días después</strong>. Esto también aplica a las entradas de un miembro que
        sale de un presupuesto compartido.
      </li>
      <li>
        <strong>Registros que sobreviven a una cuenta.</strong> Los registros de invitación y de
        membresía de un presupuesto compartido se conservan tras eliminar una cuenta. Contienen
        identificadores de usuario, fechas y el código de invitación — ningún nombre, correo ni cifra
        financiera. Contáctenos si desea que se eliminen.
      </li>
      <li>
        <strong>Datos locales.</strong> Los datos en su dispositivo permanecen allí hasta que usted los
        elimine, elimine su cuenta o desinstale la App. Cerrar sesión no elimina nada.
      </li>
      <li>
        <strong>Nuestros proveedores.</strong> Google y nuestros demás proveedores pueden conservar
        datos en copias de seguridad y registros conforme a sus propios plazos, que no controlamos.
      </li>
    </ul>

    <h2>8. Seguridad</h2>
    <p>
      Los datos en tránsito se protegen con TLS, y los datos en reposo en nuestra nube están cifrados
      por Google Cloud. El acceso a sus datos en la nube se controla mediante reglas de seguridad del
      lado del servidor vinculadas a su cuenta y, en un presupuesto compartido, a la membresía que
      usted creó. Las solicitudes a nuestras funciones de IA deben superar una verificación de
      integridad del dispositivo. Su PIN de la App, su PIN de recuperación y sus ajustes biométricos
      nunca salen de su dispositivo.
    </p>
    <p>
      <strong>
        Debemos ser francos con usted sobre dos límites. Primero, sus datos de presupuesto no tienen
        cifrado de extremo a extremo:
      </strong>{' '}
      se almacenan de una forma a la que nosotros, como operadores del servicio, podríamos
      técnicamente acceder. Solo accedemos cuando es necesario para operar el servicio, investigar un
      problema que usted reporte o cumplir la ley.{' '}
      <strong>Segundo, ningún método de transmisión o almacenamiento es completamente seguro</strong>{' '}
      y no podemos garantizar seguridad absoluta. El archivo de copia de seguridad que exporta desde
      la App <strong>no está cifrado</strong>; guárdelo en un lugar de confianza.
    </p>
    <p>
      Proteja también su lado: use un código de bloqueo en el dispositivo, active el bloqueo de la App
      y trate el código de invitación de un presupuesto compartido como una contraseña.
    </p>

    <h2>9. Menores</h2>
    <p>
      La App no está dirigida a menores de 13 años y no recopilamos a sabiendas información personal
      de ellos. Nuestros <a href="/terms">Términos de Uso</a> exigen que los titulares de cuenta
      tengan 18 años o más; una persona de 13 a 17 años solo puede usar la App bajo la supervisión de
      un padre, madre o tutor que acepte los Términos en su nombre. Si cree que un menor de 13 años
      nos ha proporcionado información personal, contáctenos en <Mail /> y la eliminaremos.
    </p>

    <h2>10. Sus derechos y opciones</h2>
    <p>Puede actuar sobre sus datos directamente en la App:</p>
    <ul>
      <li>
        <strong>Verlos y exportarlos.</strong> Perfil → Copia de seguridad e Importación exporta todo
        su conjunto de datos como archivo. Tenga en cuenta que la exportación no está cifrada.
      </li>
      <li><strong>Corregirlos.</strong> Toda entrada es editable en la App.</li>
      <li>
        <strong>Eliminar su cuenta y sus datos en la nube.</strong> Perfil → tarjeta de su cuenta →
        Eliminar cuenta. Esto borra sus datos en la nube, las imágenes de recibos subidas, su propia
        cuenta y sus datos en ese dispositivo. No se puede deshacer, y se rechaza mientras otro miembro
        siga en su presupuesto compartido — elimínelo primero.
      </li>
      <li>
        <strong>Dejar de compartir.</strong> Salga o termine un presupuesto compartido en cualquier
        momento desde la pantalla de Presupuesto Compartido.
      </li>
      <li>
        <strong>Dejar de sincronizar.</strong> Cierre sesión o deje vencer la suscripción. Cerrar
        sesión deja su copia en la nube; use Eliminar cuenta para borrarla.
      </li>
      <li>
        <strong>Si nunca inició sesión</strong>, no hay copia en la nube que eliminar. Desinstalar la
        App elimina sus datos del dispositivo.
      </li>
      <li>
        <strong>Los permisos del dispositivo</strong> — cámara, fotos y notificaciones — pueden
        cambiarse en cualquier momento en los ajustes de su dispositivo.
      </li>
    </ul>
    <p>
      Según dónde resida, puede tener derecho a <strong>acceder</strong>, <strong>rectificar</strong>,{' '}
      <strong>suprimir</strong>, <strong>portar</strong>, <strong>limitar</strong> u{' '}
      <strong>oponerse</strong> al tratamiento de sus datos personales, a{' '}
      <strong>retirar su consentimiento</strong> y a no sufrir discriminación por ejercer esos
      derechos. Los residentes de la UE, el Reino Unido, California y otros estados de EE. UU. con
      leyes de privacidad tienen estos derechos conforme al RGPD, el RGPD del Reino Unido, la
      CCPA/CPRA y leyes equivalentes.
    </p>
    <p>
      Para ejercer cualquiera de ellos, escriba a <Mail />. Verificaremos su solicitud mediante la
      cuenta desde la que se envía y responderemos dentro del plazo que exija la ley aplicable.
      Ejercer estos derechos no tiene costo y no le trataremos de forma distinta por hacerlo. Los
      usuarios de la UE y el Reino Unido también pueden presentar una reclamación ante su autoridad
      local de protección de datos.
    </p>

    <h2>11. Cambios a esta política</h2>
    <p>
      Actualizaremos esta política cuando cambie la App. La fecha de &ldquo;Última
      actualización&rdquo; en la parte superior indica cuándo. Ante cambios sustanciales haremos
      esfuerzos razonables por avisarle en la App o por otros medios. Le recomendamos consultarla
      periódicamente.
    </p>

    <h2>12. Contacto</h2>
    <p>Preguntas, solicitudes o inquietudes sobre privacidad:</p>
    <p>
      📧 <strong><Mail /></strong>
    </p>
    <p>
      Budget Your Budget — operado por Eduardo Velez, Estado Libre Asociado de Puerto Rico, Estados
      Unidos.
    </p>
  </>
);

/* ── PAGE ─────────────────────────────────────────────────── */

export default function PrivacyPolicy() {
  return (
    <LegalLayout
      en={EN}
      es={ES}
      updatedEn="September 23, 2026"
      updatedEs="23 de septiembre de 2026"
    />
  );
}
